# Справочник юнитов-кандидатов для взводов Rise of the Empire, по (планета, операция).
#
# Ключ — РЕАЛЬНОЕ НАЗВАНИЕ ПЛАНЕТЫ (английское), не фаза/этап и не ветка (dark/mixed/
# light) — по прямому запросу пользователя 2026-08-27: "жёсткая привязка к фазам не
# нужна... есть планеты, и на каждой планете есть конкретные взводы с конкретными
# персонажами". Фаза — не надёжный якорь: одна и та же планета может занимать НЕСКОЛЬКО
# этапов подряд в реальном прогрессе конкретной гильдии, если она не выбрала все звёзды
# за этап (см. комментарий в cogs/guild_events.py про TB_PLANET_CONFLICT — "Датомир на 3
# и 4 этапе, Кессель на 4 и 5" и т.п.) — единственный устойчивый идентификатор это само
# название планеты.
#
# Источник: живой ростер HotUtils (hotutils.com/tb/planning/rote/38, шаблон "!!Тест",
# гильдия AbsoluteChaos), снято 2026-08-27 через DOM (.Templates_zone-card__P1F7h /
# .Templates_character__eBfJe) — точный список из 15 донат-слотов на операцию, КАК ЕСТЬ,
# включая повторы одного и того же юнита в разных слотах (несколько игроков могут
# донатить одного персонажа). Это НЕ жёсткое игровое требование (само требование —
# генерик: сторона + мин. реликвия, подтверждено и через Comlink game-data, и через
# nameslistids в EchoBase), а текущий план гильдии AbsoluteChaos на конкретный момент —
# он дрейфует по мере прокачки гильдии (см. память
# project_tb_platoon_unit_lists_rote_2026-08-27) — переснять с HotUtils, если этот файл
# давно не обновлялся.
#
# 20 планет всего: 18 обычных (по 6 на каждую из 3 сторон — Dark/Mixed/Light) + Zeffo и
# Mandalore (бонус-зоны; в EchoBase Platoon Assigner их нет вовсе, только в HotUtils).
# Для соответствия конкретному текущему плану ТБ гильдии (какая планета сейчас на каком
# этапе) — см. распознавание активного плана в web/routes/guild_dashboard.py::tb_platoons
# (парсит опубликованные ботом блоки ордера в треде guilds.tb_active_plan_id → thread_id).

ROTE_PLATOON_SUGGESTIONS: dict[tuple[str, int], list[str]] = {
    # ---- Mustafar ----
    ("Mustafar", 1): ["BT-1", "Chimaera", "Darth Maul", "Darth Maul", "Darth Sion", "Emperor Palpatine", "Emperor Palpatine", "Gamorrean Guard", "Gauntlet Starfighter", "General Grievous", "General Grievous", "Geonosian Spy's Starfighter", "Imperial Probe Droid", "Imperial Super Commando", "Ugnaught"],
    ("Mustafar", 2): ["Asajj Ventress", "Darth Sidious", "Darth Traya", "Dengar", "Droideka", "Emperor Palpatine", "Grand Admiral Thrawn", "Grand Admiral Thrawn", "Hyena Bomber", "IG-88", "Jango Fett", "Nute Gunray", "Ugnaught", "Wat Tambor", "Wat Tambor"],
    ("Mustafar", 3): ["0-0-0", "0-0-0", "BT-1", "Chimaera", "Chimaera", "Darth Revan", "Darth Traya", "Darth Traya", "Darth Vader", "Hound's Tooth", "Imperial TIE Bomber", "Ninth Sister", "Sith Assassin", "TIE Fighter Pilot", "Wat Tambor"],
    ("Mustafar", 4): ["0-0-0", "B1 Battle Droid", "Dark Trooper", "Darth Revan", "Darth Revan", "Darth Sion", "Darth Traya", "Embo", "General Grievous", "General Grievous", "Grand Admiral Thrawn", "Hound's Tooth", "IG-86 Sentinel Droid", "Sith Trooper", "Ugnaught"],
    ("Mustafar", 5): ["0-0-0", "Boba Fett", "Canderous Ordo", "Chimaera", "Chimaera", "Darth Traya", "Darth Traya", "Darth Traya", "Droideka", "Emperor Palpatine", "First Order SF TIE Pilot", "IG-88", "Mara Jade, The Emperor's Hand", "Nightsister Initiate", "Tusken Shaman"],
    ("Mustafar", 6): ["Canderous Ordo", "Chimaera", "Count Dooku", "Darth Revan", "Darth Revan", "Darth Sidious", "Darth Vader", "Fifth Brother", "First Order Officer", "First Order Officer", "First Order SF TIE Pilot", "General Grievous", "Imperial Probe Droid", "Imperial TIE Fighter", "Wat Tambor"],
    # ---- Corellia ----
    ("Corellia", 1): ["Anakin's Eta-2 Starfighter", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "C-3PO", "Chewbacca", "Commander Ahsoka Tano", "Darth Revan", "Darth Traya", "Eeth Koth", "Grand Admiral Thrawn", "Hyena Bomber", "Ima-Gun Di", "Jedi Knight Revan", "R2-D2", "Sith Trooper"],
    ("Corellia", 2): ["Ben Solo", "Boba Fett, Scion of Jango", "BT-1", "C-3PO", "Commander Luke Skywalker", "Commander Luke Skywalker", "Darth Malgus", "Darth Revan", "Geonosian Brood Alpha", "Grand Master Yoda", "Han Solo", "Hunter", "Jolee Bindo", "Poe Dameron", "The Mandalorian (Beskar Armor)"],
    ("Corellia", 3): ["Boba Fett, Scion of Jango", "Bossk", "Chewbacca", "Clone Sergeant's ARC-170", "Commander Luke Skywalker", "Darth Revan", "Ghost", "Grand Master Yoda", "Padmé Amidala", "Paploo", "Rey (Jedi Training)", "Threepio & Chewie", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "Wat Tambor"],
    ("Corellia", 4): ["BB-8", "Ben Solo", "C-3PO", "Clone Sergeant - Phase I", "Commander Ahsoka Tano", "Darth Malgus", "Darth Revan", "Darth Traya", "Darth Traya", "Darth Vader", "Ki-Adi-Mundi", "Kylo Ren's Command Shuttle", "Plo Koon's Jedi Starfighter", "Rebel Officer Leia Organa", "T3-M4"],
    ("Corellia", 5): ["Boba Fett, Scion of Jango", "Chewbacca", "Chimaera", "Colonel Starck", "Commander Ahsoka Tano", "Darth Maul", "General Kenobi", "Geonosian Brood Alpha", "Han Solo", "Logray", "Malevolence", "R2-D2", "Razor Crest", "TIE Silencer", "Wat Tambor"],
    ("Corellia", 6): ["Admiral Piett", "Darth Revan", "Darth Sion", "Emperor Palpatine", "General Kenobi", "Hermit Yoda", "Imperial Probe Droid", "Jawa Engineer", "Ki-Adi-Mundi", "Sana Starros", "Talia", "The Mandalorian (Beskar Armor)", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    # ---- Coruscant ----
    ("Coruscant", 1): ["Barriss Offee", "BB-8", "CC-2224 \"Cody\"", "Commander Luke Skywalker", "General Skywalker", "General Skywalker", "Greef Karga", "Hermit Yoda", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "L3-37", "Phantom II", "R2-D2", "Rey (Jedi Training)", "The Mandalorian (Beskar Armor)"],
    ("Coruscant", 2): ["BB-8", "BB-8", "Chewbacca", "Chewbacca", "General Skywalker", "General Skywalker", "General Skywalker", "Hermit Yoda", "Home One", "Jyn Erso", "Resistance X-wing", "Sana Starros", "Sana Starros", "The Mandalorian (Beskar Armor)", "The Mandalorian (Beskar Armor)"],
    ("Coruscant", 3): ["Ahsoka Tano (Fulcrum)", "BB-8", "C-3PO", "Grand Master Yoda", "Hermit Yoda", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Padmé Amidala", "R2-D2", "Rey (Jedi Training)", "Sana Starros", "The Armorer", "Threepio & Chewie", "Umbaran Starfighter"],
    ("Coruscant", 4): ["Anakin's Eta-2 Starfighter", "C-3PO", "General Kenobi", "General Skywalker", "General Skywalker", "Han Solo", "Han Solo", "Hondo Ohnaka", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Lobot", "Logray", "Plo Koon's Jedi Starfighter", "The Mandalorian (Beskar Armor)", "Visas Marr"],
    ("Coruscant", 5): ["BB-8", "Commander Luke Skywalker", "General Kenobi", "Han Solo", "Hermit Yoda", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jolee Bindo", "Kuiil", "Logray", "Phantom II", "Teebo", "The Mandalorian (Beskar Armor)", "Threepio & Chewie"],
    ("Coruscant", 6): ["Amilyn Holdo", "C-3PO", "General Skywalker", "General Skywalker", "General Skywalker", "Grand Master Yoda", "Hermit Yoda", "Hermit Yoda", "Jedi Knight Revan", "Ki-Adi-Mundi", "Raven's Claw", "Rebel Officer Leia Organa", "Sabine Wren", "Sana Starros", "Zaalbar"],
    # ---- Geonosis ----
    ("Geonosis", 1): ["Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Chimaera", "Darth Revan", "Executrix", "HK-47", "Imperial Probe Droid", "Imperial Probe Droid", "Maul", "Scimitar", "Scythe", "Scythe", "Sith Eternal Emperor", "Starkiller", "Wat Tambor"],
    ("Geonosis", 2): ["B2 Super Battle Droid", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Darth Malak", "Darth Malgus", "Darth Revan", "Darth Talon", "Dengar", "Droideka", "Grand Admiral Thrawn", "Kylo Ren (Unmasked)", "Maul", "Scythe", "Supreme Leader Kylo Ren", "TIE Reaper"],
    ("Geonosis", 3): ["Asajj Ventress", "Boba Fett, Scion of Jango", "Chimaera", "Darth Malak", "Darth Malgus", "Darth Revan", "Darth Revan", "Emperor Palpatine", "First Order Officer", "General Veers", "Grand Admiral Thrawn", "Scythe", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Geonosis", 4): ["Chimaera", "Darth Malgus", "Darth Revan", "Emperor's Shuttle", "Executor", "First Order Officer", "General Grievous", "Grand Inquisitor", "Grand Inquisitor", "Imperial Probe Droid", "Scythe", "TIE Echelon", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "Wat Tambor"],
    ("Geonosis", 5): ["B2 Super Battle Droid", "Boba Fett, Scion of Jango", "Cad Bane", "Colonel Starck", "Darth Malgus", "Emperor Palpatine", "Emperor Palpatine", "Grand Admiral Thrawn", "Kylo Ren (Unmasked)", "Magmatrooper", "Malevolence", "Maul", "Sith Eternal Emperor", "Starkiller", "Starkiller"],
    ("Geonosis", 6): ["Boba Fett, Scion of Jango", "Chimaera", "Darth Malak", "Darth Malgus", "Darth Revan", "Death Trooper", "Emperor Palpatine", "Executor", "Grand Admiral Thrawn", "Grand Inquisitor", "Hyena Bomber", "Kylo Ren's Command Shuttle", "Maul", "Scythe", "TIE/IN Interceptor Prototype"],
    # ---- Felucia ----
    ("Felucia", 1): ["Aayla Secura", "Ben Solo", "Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "General Kenobi", "General Skywalker", "Grand Inquisitor", "Plo Koon's Jedi Starfighter", "Razor Crest", "Rebel Officer Leia Organa", "Scythe", "Sith Eternal Emperor", "Threepio & Chewie", "TIE/IN Interceptor Prototype", "Wat Tambor"],
    ("Felucia", 2): ["Commander Ahsoka Tano", "Commander Ahsoka Tano", "Darth Malgus", "Embo", "Emperor's Shuttle", "General Skywalker", "Jawa", "Jedi Knight Luke Skywalker", "Jedi Master Luke Skywalker", "Maul", "Outrider", "Scythe", "The Mandalorian", "TIE/IN Interceptor Prototype", "Zaalbar"],
    ("Felucia", 3): ["Ben Solo", "Commander Ahsoka Tano", "General Hux", "Imperial Probe Droid", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Lord Vader", "Maul", "Razor Crest", "Rebel Officer Leia Organa", "Sana Starros", "Scythe", "Scythe", "Snowtrooper", "Wat Tambor"],
    ("Felucia", 4): ["Boba Fett, Scion of Jango", "Count Dooku", "Darth Malgus", "General Skywalker", "General Veers", "Grand Inquisitor", "Hermit Yoda", "Kuiil", "Logray", "Maul", "Maul", "Rebel Officer Leia Organa", "Scythe", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype"],
    ("Felucia", 5): ["Admiral Ackbar", "Bastila Shan", "Boba Fett, Scion of Jango", "Cassian's U-wing", "Commander Ahsoka Tano", "Darth Malgus", "Darth Malgus", "Death Trooper", "Embo", "General Skywalker", "Grand Inquisitor", "Razor Crest", "Rey", "Scythe", "Sith Trooper"],
    ("Felucia", 6): ["Ben Solo", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "BT-1", "Commander Ahsoka Tano", "Darth Malak", "Darth Malgus", "Han Solo", "Ki-Adi-Mundi", "L3-37", "Lando Calrissian", "Rebel Officer Leia Organa", "Scythe", "Sith Eternal Emperor", "Starkiller"],
    # ---- Bracca ----
    ("Bracca", 1): ["Admiral Raddus", "Boushh (Leia Organa)", "BTL-B Y-wing Starfighter", "Clone Sergeant - Phase I", "Commander Ahsoka Tano", "Ghost", "Juhani", "L3-37", "Outrider", "Poe Dameron's X-wing", "R2-D2", "Razor Crest", "Razor Crest", "Rey", "Wedge Antilles"],
    ("Bracca", 2): ["Aayla Secura", "ARC Trooper", "BB-8", "Ben Solo", "BTL-B Y-wing Starfighter", "C-3PO", "Chewbacca", "Jedi Consular's Starfighter", "Jedi Knight Revan", "Mon Mothma", "Pao", "Profundity", "Razor Crest", "Razor Crest", "Young Han Solo"],
    ("Bracca", 3): ["BB-8", "Ben Solo", "Ben Solo", "Ben Solo", "CT-21-0408 \"Echo\"", "Ebon Hawk", "Endurance", "Enfys Nest", "Grand Master Yoda", "Grand Master Yoda", "Greef Karga", "Jedi Master Kenobi", "Kanan Jarrus", "Rey (Jedi Training)", "Rose Tico"],
    ("Bracca", 4): ["Ben Solo", "Ben Solo", "Bodhi Rook", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "CT-5555 \"Fives\"", "Ghost", "Greef Karga", "Omega", "Profundity", "R2-D2", "Razor Crest", "Razor Crest", "Threepio & Chewie", "Veteran Smuggler Chewbacca"],
    ("Bracca", 5): ["Ben Solo", "Ben Solo", "Bistan's U-wing", "Chewbacca", "Commander Ahsoka Tano", "Ezra Bridger", "Grand Master Yoda", "Han's Millennium Falcon", "Jedi Master Kenobi", "Kanan Jarrus", "Outrider", "Razor Crest", "Razor Crest", "Razor Crest", "Rey (Jedi Training)"],
    ("Bracca", 6): ["Ben Solo", "Ben Solo", "C-3PO", "Commander Ahsoka Tano", "Commander Luke Skywalker", "CT-7567 \"Rex\"", "Grand Master Yoda", "Padmé Amidala", "Raven's Claw", "Razor Crest", "Razor Crest", "Razor Crest", "Rey", "Teebo", "Vandor Chewbacca"],
    # ---- Dathomir ----
    ("Dathomir", 1): ["Darth Malgus", "Darth Malgus", "Darth Maul", "Darth Traya", "Dengar", "First Order SF TIE Fighter", "General Grievous", "General Grievous", "Geonosian Spy's Starfighter", "Lord Vader", "Maul", "Scythe", "Sith Eternal Emperor", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Dathomir", 2): ["Boba Fett, Scion of Jango", "General Grievous", "General Hux", "Imperial Probe Droid", "Lord Vader", "Maul", "Savage Opress", "Scythe", "Scythe", "Sith Eternal Emperor", "Talia", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "Tusken Raider", "Wat Tambor"],
    ("Dathomir", 3): ["Dark Trooper", "Darth Malgus", "HK-47", "Hyena Bomber", "Imperial Probe Droid", "Lord Vader", "Maul", "Maul", "Scythe", "Scythe", "Sith Assassin", "Sith Eternal Emperor", "TIE/IN Interceptor Prototype", "Wat Tambor", "Wat Tambor"],
    ("Dathomir", 4): ["Boba Fett, Scion of Jango", "Cad Bane", "Darth Malgus", "Darth Malgus", "Darth Revan", "Dengar", "IG-88", "Lord Vader", "Lord Vader", "Maul", "Mother Talzin", "Scythe", "Scythe", "Sith Trooper", "TIE Advanced x1"],
    ("Dathomir", 5): ["0-0-0", "Darth Malgus", "Darth Malgus", "Emperor's Shuttle", "First Order SF TIE Pilot", "Gar Saxon", "Grand Admiral Thrawn", "Grand Moff Tarkin", "Lord Vader", "Scythe", "Seventh Sister", "Sith Eternal Emperor", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Dathomir", 6): ["Aurra Sing", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Chimaera", "Darth Malgus", "Darth Malgus", "Director Krennic", "Embo", "Geonosian Soldier's Starfighter", "Imperial TIE Fighter", "Maul", "Scythe", "Supreme Leader Kylo Ren", "Supreme Leader Kylo Ren", "Tusken Raider"],
    # ---- Tatooine ----
    ("Tatooine", 1): ["Bastila Shan (Fallen)", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Cara Dune", "Chirrut Îmwe", "Commander Ahsoka Tano", "Darth Malgus", "Gauntlet Starfighter", "Geonosian Spy", "Maul", "Razor Crest", "Rey", "Sith Eternal Emperor", "TIE/IN Interceptor Prototype", "Tusken Chieftain"],
    ("Tatooine", 2): ["50R-T", "Bastila Shan (Fallen)", "Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "Jedi Master Kenobi", "Maul", "Nightsister Acolyte", "Obi-Wan Kenobi (Old Ben)", "Outrider", "Qui-Gon Jinn", "Razor Crest", "Scythe", "Sith Eternal Emperor", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Tatooine", 3): ["Ben Solo", "Boba Fett, Scion of Jango", "Darth Malgus", "Darth Malgus", "Ewok Scout", "Hunter", "Jedi Master Kenobi", "Luminara Unduli", "Mara Jade, The Emperor's Hand", "Maul", "Razor Crest", "Rose Tico", "Scythe", "Skiff Guard (Lando Calrissian)", "Supreme Leader Kylo Ren"],
    ("Tatooine", 4): ["Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "Coruscant Underworld Police", "Darth Malak", "Ewok Elder", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Kylo Ren (Unmasked)", "Razor Crest", "Resistance Hero Poe", "Scythe", "Starkiller", "TIE Reaper", "Young Han Solo"],
    ("Tatooine", 5): ["B1 Battle Droid", "Bodhi Rook", "Darth Malgus", "Finalizer", "General Skywalker", "HK-47", "Hoth Rebel Scout", "Jedi Knight Luke Skywalker", "Jedi Master Luke Skywalker", "Maul", "Rey", "Scythe", "Starkiller", "Teebo", "TIE/IN Interceptor Prototype"],
    ("Tatooine", 6): ["Barriss Offee", "Boba Fett, Scion of Jango", "Darth Malak", "Darth Malgus", "First Order SF TIE Fighter", "Hondo Ohnaka", "IG-2000", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Maul", "Obi-Wan Kenobi (Old Ben)", "Resistance Hero Finn", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype"],
    # ---- Kashyyyk ----
    ("Kashyyyk", 1): ["C-3PO", "Commander Ahsoka Tano", "Han Solo", "Hermit Yoda", "Hermit Yoda", "Jedi Knight Anakin", "Jedi Master Luke Skywalker", "Logray", "Mace Windu", "Padmé Amidala", "R2-D2", "R2-D2", "Razor Crest", "Razor Crest", "Rey"],
    ("Kashyyyk", 2): ["BB-8", "BB-8", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Commander Luke Skywalker", "Han's Millennium Falcon", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Kenobi", "Ki-Adi-Mundi", "Ki-Adi-Mundi", "Logray", "Logray", "Raven's Claw", "Razor Crest"],
    ("Kashyyyk", 3): ["Ben Solo", "Clone Sergeant - Phase I", "Commander Ahsoka Tano", "General Kenobi", "Grand Master Yoda", "Greef Karga", "Han's Millennium Falcon", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "R2-D2", "Razor Crest", "Rebel Officer Leia Organa", "Rebel Officer Leia Organa", "Skiff Guard (Lando Calrissian)"],
    ("Kashyyyk", 4): ["BB-8", "Ben Solo", "C-3PO", "Commander Ahsoka Tano", "CT-5555 \"Fives\"", "Greef Karga", "Han's Millennium Falcon", "Hoth Rebel Scout", "Lando's Millennium Falcon", "Logray", "R2-D2", "Razor Crest", "Resistance Trooper", "Rey", "Rey"],
    ("Kashyyyk", 5): ["Ben Solo", "Ben Solo", "C-3PO", "Commander Ahsoka Tano", "Commander Luke Skywalker", "Grand Master Yoda", "Greef Karga", "Greef Karga", "Greef Karga", "Jedi Master Luke Skywalker", "K-2SO", "Logray", "Padmé Amidala", "Rey", "Rey (Jedi Training)"],
    ("Kashyyyk", 6): ["Ben Solo", "Ben Solo", "Commander Luke Skywalker", "Ewok Scout", "Han Solo", "Han's Millennium Falcon", "Han's Millennium Falcon", "Hoth Rebel Soldier", "Jedi Knight Revan", "Jedi Master Luke Skywalker", "Negotiator", "Padmé Amidala", "Razor Crest", "Resistance Trooper", "Rey"],
    # ---- Zeffo ----
    ("Zeffo", 1): ["BB-8", "Chirrut Îmwe", "Commander Ahsoka Tano", "General Kenobi", "General Skywalker", "Han Solo", "Jedi Consular", "Jedi Consular's Starfighter", "Jedi Knight Luke Skywalker", "Jedi Master Luke Skywalker", "Jolee Bindo", "Ki-Adi-Mundi", "Kyle Katarn", "MG-100 StarFortress SF-17", "Rey"],
    ("Zeffo", 2): ["Chewbacca", "Chief Chirpa", "Clone Sergeant - Phase I", "General Skywalker", "Han Solo", "Hermit Yoda", "Home One", "Jedi Knight Guardian", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Jedi Master Kenobi", "Ki-Adi-Mundi", "Kyle Katarn", "Razor Crest", "Rex's ARC-170"],
    ("Zeffo", 3): ["Ben Solo", "C-3PO", "Clone Sergeant - Phase I", "General Kenobi", "General Skywalker", "Han Solo", "Jedi Consular", "Jedi Knight Luke Skywalker", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Juhani", "Ki-Adi-Mundi", "Kyle Katarn", "MG-100 StarFortress SF-17", "Raddus"],
    ("Zeffo", 4): ["Ben Solo", "Commander Luke Skywalker", "General Skywalker", "Jedi Knight Guardian", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Luke Skywalker", "Jolee Bindo", "Ki-Adi-Mundi", "Kit Fisto", "Luke Skywalker (Farmboy)", "Qi'ra", "Rey", "Rey (Jedi Training)", "Wrecker"],
    ("Zeffo", 5): ["Ben Solo", "Chief Chirpa", "Commander Luke Skywalker", "Enfys Nest", "Garazeb \"Zeb\" Orrelios", "General Skywalker", "Jedi Consular", "Jedi Knight Luke Skywalker", "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "Luke Skywalker (Farmboy)", "Mission Vao", "R2-D2", "Rey", "Rey (Jedi Training)"],
    ("Zeffo", 6): ["Chirrut Îmwe", "Clone Sergeant's ARC-170", "Commander Luke Skywalker", "General Skywalker", "Jedi Knight Guardian", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Jedi Master Kenobi", "Jolee Bindo", "Ki-Adi-Mundi", "Padmé Amidala", "Plo Koon", "Razor Crest", "Rey (Jedi Training)", "Visas Marr"],
    # ---- Haven-class Medical Station ----
    ("Haven-class Medical Station", 1): ["Bastila Shan (Fallen)", "BT-1", "Darth Malak", "Darth Vader", "Embo", "Executor", "Lord Vader", "Maul", "Nightsister Spirit", "Range Trooper", "Scythe", "Scythe", "Sith Eternal Emperor", "Starkiller", "Starkiller"],
    ("Haven-class Medical Station", 2): ["Aurra Sing", "Boba Fett, Scion of Jango", "Cad Bane", "Darth Malak", "First Order Stormtrooper", "Iden Versio", "Nightsister Zombie", "Sith Eternal Emperor", "Sith Eternal Emperor", "Snowtrooper", "Starkiller", "Starkiller", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Haven-class Medical Station", 3): ["Darth Malak", "Darth Malgus", "Darth Malgus", "Darth Maul", "Dengar", "Executor", "Hyena Bomber", "Lord Vader", "Nightsister Initiate", "Snowtrooper", "Starkiller", "Starkiller", "Supreme Leader Kylo Ren", "TIE Silencer", "TIE/IN Interceptor Prototype"],
    ("Haven-class Medical Station", 4): ["Asajj Ventress", "Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Director Krennic", "Eighth Brother", "HK-47", "IG-88", "Krrsantan", "Lord Vader", "Lord Vader", "Nightsister Acolyte", "Scythe", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype", "Wampa"],
    ("Haven-class Medical Station", 5): ["Asajj Ventress", "Aurra Sing", "Executor", "General Veers", "Hyena Bomber", "Mara Jade, The Emperor's Hand", "Maul", "Maul", "Savage Opress", "Scythe", "Second Sister", "Seventh Sister", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "TIE/IN Interceptor Prototype"],
    ("Haven-class Medical Station", 6): ["B2 Super Battle Droid", "Boba Fett, Scion of Jango", "Dathcha", "Emperor's Shuttle", "Emperor's Shuttle", "Executor", "First Order TIE Pilot", "Hondo Ohnaka", "Lord Vader", "Malevolence", "Scythe", "Supreme Leader Kylo Ren", "TIE Fighter Pilot", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    # ---- Kessel ----
    ("Kessel", 1): ["Boba Fett, Scion of Jango", "Coruscant Underworld Police", "Ebon Hawk", "Executor", "General Skywalker", "Jedi Consular's Starfighter", "Jedi Knight Luke Skywalker", "Lord Vader", "Outrider", "Poggle the Lesser", "Rey", "Starkiller", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Kessel", 2): ["Aurra Sing", "Ben Solo", "Darth Malak", "Darth Malgus", "Echo", "Gamorrean Guard", "Jedi Master Kenobi", "Maul", "Razor Crest", "Rex's ARC-170", "Rey", "Sith Eternal Emperor", "Sith Fighter", "Starkiller", "Starkiller"],
    ("Kessel", 3): ["General Skywalker", "Nightsister Initiate", "Nightsister Initiate", "Razor Crest", "Scythe", "Seventh Sister", "Sith Eternal Emperor", "Sith Eternal Emperor", "Slave I", "Starkiller", "Starkiller", "Supreme Leader Kylo Ren", "The Mandalorian", "TIE/IN Interceptor Prototype", "TIE/IN Interceptor Prototype"],
    ("Kessel", 4): ["Baze Malbus", "Ben Solo", "Bistan", "Bo-Katan Kryze", "Darth Malgus", "General Skywalker", "General Veers", "Hoth Rebel Soldier", "Jedi Knight Luke Skywalker", "Lord Vader", "Maul", "Rey", "Rey", "Scythe", "Starkiller"],
    ("Kessel", 5): ["50R-T", "Asajj Ventress", "B-28 Extinction-class Bomber", "Boba Fett, Scion of Jango", "Executor", "General Skywalker", "IG-88", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Maul", "Razor Crest", "Rebel Y-wing", "Rey", "Scythe", "Sith Eternal Emperor"],
    ("Kessel", 6): ["Admiral Ackbar", "Ben Solo", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Dark Trooper", "Darth Malak", "Darth Malak", "Kylo Ren", "Razor Crest", "Rey", "Sith Empire Trooper", "Sith Eternal Emperor", "Starkiller", "Supreme Leader Kylo Ren", "TIE Silencer"],
    # ---- Lothal ----
    ("Lothal", 1): ["Ben Solo", "Dash Rendar", "Han Solo", "Hermit Yoda", "Jedi Knight Revan", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Profundity", "Razor Crest", "Razor Crest", "Rebel Officer Leia Organa", "Rebel Y-wing", "Veteran Smuggler Chewbacca", "Xanadu Blood", "Zaalbar"],
    ("Lothal", 2): ["BB-8", "Chewbacca", "Chewbacca", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "General Kenobi", "Hermit Yoda", "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "Profundity", "Profundity", "The Mandalorian (Beskar Armor)", "Xanadu Blood", "Zaalbar"],
    ("Lothal", 3): ["50R-T", "Ben Solo", "Chief Nebit", "Commander Ahsoka Tano", "Ebon Hawk", "Finn", "Hermit Yoda", "Hermit Yoda", "Ki-Adi-Mundi", "Profundity", "Profundity", "R2-D2", "Raven's Claw", "Razor Crest", "Rey"],
    ("Lothal", 4): ["Commander Ahsoka Tano", "Eeth Koth", "General Kenobi", "Ghost", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Jolee Bindo", "Kyle Katarn", "Outrider", "Profundity", "Rebel Officer Leia Organa", "Rebel Officer Leia Organa", "Rey (Jedi Training)", "Scarif Rebel Pathfinder", "Scarif Rebel Pathfinder"],
    ("Lothal", 5): ["Bistan", "Grand Master Yoda", "Han Solo", "Han's Millennium Falcon", "Jedi Consular", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Kenobi", "Logray", "Logray", "Padmé Amidala", "Plo Koon's Jedi Starfighter", "Profundity", "Razor Crest", "Tech"],
    ("Lothal", 6): ["50R-T", "Aayla Secura", "Ben Solo", "Echo", "General Kenobi", "Hermit Yoda", "Hondo Ohnaka", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Padmé Amidala", "Rebel Officer Leia Organa", "Sana Starros", "Wedge Antilles's X-wing", "Wicket"],
    # ---- Mandalore ----
    ("Mandalore", 1): ["Ben Solo", "Captain Drogan", "Cere Junda", "Comeuppance", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Darth Malak", "Doctor Aphra", "Kelleran Beq", "Leia Organa", "Leviathan", "Princess Kneesaa", "Rey", "Sith Eternal Emperor", "Wat Tambor"],
    ("Mandalore", 2): ["Admiral Trench", "Boba Fett, Scion of Jango", "Captain Drogan", "Comeuppance", "Comeuppance", "Doctor Aphra", "Executor", "Fury-class Interceptor", "General Skywalker", "Jedi Knight Luke Skywalker", "Lord Vader", "Sith Eternal Emperor", "Tarfful", "Taron Malicos", "TIE Dagger"],
    ("Mandalore", 3): ["Admiral Trench", "Captain Rex", "Commander Ahsoka Tano", "Darth Bane", "General Skywalker", "Kelleran Beq", "Ki-Adi-Mundi", "Leia Organa", "Lord Vader", "Mark VI Interceptor", "Rey", "Scythe", "Starkiller", "Tusken Chieftain", "Tusken Warrior"],
    ("Mandalore", 4): ["Captain Rex", "Doctor Aphra", "Fury-class Interceptor", "Jedi Master Kenobi", "Leia Organa", "Leviathan", "Leviathan", "Merrin", "Princess Kneesaa", "Razor Crest", "Starkiller", "Supreme Leader Kylo Ren", "Tarfful", "TIE/IN Interceptor Prototype", "Wat Tambor"],
    ("Mandalore", 5): ["Cere Junda", "Darth Malgus", "Doctor Aphra", "Executor", "Fury-class Interceptor", "Ki-Adi-Mundi", "Leviathan", "Mark VI Interceptor", "Merrin", "Profundity", "Sith Eternal Emperor", "STAP", "Starkiller", "Taron Malicos", "Tusken Warrior"],
    ("Mandalore", 6): ["Admiral Trench", "Ben Solo", "Cere Junda", "Coruscant Underworld Police", "Darth Bane", "Executor", "General Skywalker", "Jedi Knight Luke Skywalker", "Leia Organa", "Lord Vader", "STAP", "Taron Malicos", "TIE Dagger", "TIE Dagger", "Wat Tambor"],
    # ---- Malachor ----
    ("Malachor", 1): ["Boba Fett", "Boba Fett, Scion of Jango", "Darth Malak", "Darth Malgus", "Darth Malgus", "Executor", "Executor", "First Order SF TIE Pilot", "Grand Inquisitor", "Scythe", "Sith Assassin", "Sith Empire Trooper", "Sith Eternal Emperor", "Starkiller", "Vulture Droid"],
    ("Malachor", 2): ["Boba Fett, Scion of Jango", "Darth Malak", "Darth Malgus", "First Order SF TIE Pilot", "Grand Inquisitor", "Kylo Ren", "Lord Vader", "Lord Vader", "Nightsister Zombie", "Scythe", "Scythe", "Starkiller", "Supreme Leader Kylo Ren", "Talia", "Tusken Shaman"],
    ("Malachor", 3): ["Boba Fett, Scion of Jango", "Darth Malak", "Darth Malak", "Executor", "First Order TIE Pilot", "Gauntlet Starfighter", "IG-88", "Jango Fett", "Lord Vader", "Lord Vader", "Maul", "Scythe", "Scythe", "Starkiller", "Wampa"],
    ("Malachor", 4): ["Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Count Dooku", "Darth Malak", "Darth Malgus", "Executrix", "Geonosian Soldier", "Geonosian Soldier's Starfighter", "Hyena Bomber", "Sith Eternal Emperor", "Sith Eternal Emperor", "Snowtrooper", "Starkiller", "Starkiller", "Supreme Leader Kylo Ren"],
    ("Malachor", 5): ["Boba Fett, Scion of Jango", "Colonel Starck", "Darth Malgus", "Executor", "Grand Inquisitor", "IG-2000", "IG-88", "Kylo Ren (Unmasked)", "Magmatrooper", "Scythe", "Sith Empire Trooper", "Sith Eternal Emperor", "Starkiller", "Starkiller", "Supreme Leader Kylo Ren"],
    ("Malachor", 6): ["B-28 Extinction-class Bomber", "Boba Fett, Scion of Jango", "Darth Malak", "Executor", "First Order Officer", "First Order TIE Fighter", "Iden Versio", "IG-88", "Maul", "Maul", "Moff Gideon", "Sith Eternal Emperor", "Sith Eternal Emperor", "Starkiller", "Starkiller"],
    # ---- Vandor ----
    ("Vandor", 1): ["Ahsoka Tano (Fulcrum)", "Ben Solo", "Commander Ahsoka Tano", "Executor", "Gauntlet Starfighter", "Hound's Tooth", "Imperial TIE Bomber", "Jedi Consular's Starfighter", "Profundity", "Resistance Hero Finn", "Scythe", "Sith Eternal Emperor", "Starkiller", "Wedge Antilles's X-wing", "Wicket"],
    ("Vandor", 2): ["50R-T", "Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "Darth Malak", "Darth Malak", "Darth Malgus", "Darth Sidious", "Grand Inquisitor", "Hondo Ohnaka", "Hunter", "Jedi Master Luke Skywalker", "Jolee Bindo", "Profundity", "Profundity", "Starkiller"],
    ("Vandor", 3): ["Barriss Offee", "Bastila Shan", "Bistan", "Bodhi Rook", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "IG-100 MagnaGuard", "Kylo Ren", "Old Daka", "Profundity", "Rey", "Scythe", "Sith Eternal Emperor", "Starkiller", "Tusken Shaman"],
    ("Vandor", 4): ["Anakin's Eta-2 Starfighter", "Boba Fett, Scion of Jango", "Darth Malak", "Grand Inquisitor", "Hyena Bomber", "Jedi Consular's Starfighter", "Jedi Knight Luke Skywalker", "Mace Windu", "Padmé Amidala", "Profundity", "Raven's Claw", "Razor Crest", "Scythe", "Supreme Leader Kylo Ren", "Supreme Leader Kylo Ren"],
    ("Vandor", 5): ["Ben Solo", "Commander Ahsoka Tano", "Emperor Palpatine", "First Order Executioner", "General Skywalker", "General Skywalker", "General Skywalker", "Grand Inquisitor", "Grand Inquisitor", "Jedi Master Kenobi", "Jedi Master Kenobi", "Jedi Master Kenobi", "Maul", "Starkiller", "Talia"],
    ("Vandor", 6): ["Chewbacca", "Commander Ahsoka Tano", "Darth Malgus", "Echo", "Executor", "Grand Inquisitor", "Grand Inquisitor", "Grand Inquisitor", "Hyena Bomber", "Jedi Master Luke Skywalker", "Lord Vader", "Nightsister Initiate", "Old Daka", "Razor Crest", "TIE Echelon"],
    # ---- Ring of Kafrene ----
    ("Ring of Kafrene", 1): ["50R-T", "Bastila Shan", "Boushh (Leia Organa)", "Commander Luke Skywalker", "Eeth Koth", "General Skywalker", "Grand Master Yoda", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Wedge Antilles's X-wing", "Zaalbar"],
    ("Ring of Kafrene", 2): ["Commander Luke Skywalker", "CT-7567 \"Rex\"", "Eeth Koth", "General Skywalker", "Grand Master Yoda", "Grand Master Yoda", "Grand Master Yoda", "Han's Millennium Falcon", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Lobot", "Padmé Amidala", "Rey", "Rey"],
    ("Ring of Kafrene", 3): ["C-3PO", "Clone Sergeant's ARC-170", "Echo", "General Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "R2-D2", "Rey", "T3-M4", "Tech", "The Armorer", "Wedge Antilles's X-wing"],
    ("Ring of Kafrene", 4): ["Amilyn Holdo", "Barriss Offee", "Baze Malbus", "C-3PO", "Chopper", "Clone Wars Chewbacca", "General Skywalker", "General Skywalker", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Mon Mothma", "Negotiator", "Profundity", "Resistance Trooper", "Rey"],
    ("Ring of Kafrene", 5): ["50R-T", "Baze Malbus", "Bodhi Rook", "Chewbacca", "General Skywalker", "Grand Master Yoda", "Hoth Rebel Soldier", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Profundity", "R2-D2", "Veteran Smuggler Chewbacca"],
    ("Ring of Kafrene", 6): ["Chirrut Îmwe", "Commander Luke Skywalker", "General Skywalker", "Ghost", "Ima-Gun Di", "Jedi Knight Luke Skywalker", "Jedi Knight Luke Skywalker", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Lando Calrissian", "Omega", "Rose Tico", "Tech", "Umbaran Starfighter"],
    # ---- Death Star ----
    ("Death Star", 1): ["Boba Fett, Scion of Jango", "Executrix", "Geonosian Spy's Starfighter", "Hondo Ohnaka", "Hyena Bomber", "Imperial Super Commando", "Lord Vader", "Maul", "Maul", "Nightsister Acolyte", "Ninth Sister", "Savage Opress", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "Ugnaught"],
    ("Death Star", 2): ["B1 Battle Droid", "Boba Fett, Scion of Jango", "Count Dooku", "Emperor's Shuttle", "Executor", "Executor", "Imperial Super Commando", "Krrsantan", "Lord Vader", "Malevolence", "Maul", "Nightsister Spirit", "Royal Guard", "Scythe", "Ugnaught"],
    ("Death Star", 3): ["Boba Fett, Scion of Jango", "Darth Malgus", "Darth Talon", "Executor", "Hondo Ohnaka", "Hound's Tooth", "Hyena Bomber", "IG-88", "Jawa Engineer", "Lord Vader", "Malevolence", "Mara Jade, The Emperor's Hand", "Maul", "Supreme Leader Kylo Ren", "URoRRuR'R'R"],
    ("Death Star", 4): ["Asajj Ventress", "Boba Fett, Scion of Jango", "Count Dooku", "Darth Malgus", "Darth Maul", "General Hux", "Geonosian Brood Alpha", "IG-100 MagnaGuard", "Jawa", "Lord Vader", "Lord Vader", "Range Trooper", "Scythe", "Shoretrooper", "Sith Eternal Emperor"],
    ("Death Star", 5): ["Boba Fett, Scion of Jango", "Boba Fett, Scion of Jango", "Darth Malgus", "Emperor's Shuttle", "Executor", "Fifth Brother", "Geonosian Soldier", "Geonosian Spy", "Grand Moff Tarkin", "HK-47", "Lord Vader", "Nightsister Acolyte", "Sith Trooper", "Supreme Leader Kylo Ren", "Tusken Raider"],
    ("Death Star", 6): ["B2 Super Battle Droid", "Darth Malgus", "Executor", "Geonosian Brood Alpha", "Hondo Ohnaka", "Hyena Bomber", "IG-86 Sentinel Droid", "IG-88", "Jawa Scavenger", "Kylo Ren (Unmasked)", "Lord Vader", "Maul", "Scythe", "Supreme Leader Kylo Ren", "Zam Wesell"],
    # ---- Hoth ----
    ("Hoth", 1): ["Commander Ahsoka Tano", "Darth Malgus", "Darth Traya", "General Kenobi", "IG-100 MagnaGuard", "Imperial Probe Droid", "Maul", "Ninth Sister", "Old Daka", "Rey", "Rey", "Sana Starros", "Scythe", "Sith Trooper", "Supreme Leader Kylo Ren"],
    ("Hoth", 2): ["Ben Solo", "Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "Darth Malgus", "Darth Malgus", "Darth Traya", "Imperial Probe Droid", "Jedi Master Kenobi", "Maul", "Outrider", "Rey", "Scythe", "Sith Empire Trooper", "Supreme Leader Kylo Ren", "Wat Tambor"],
    ("Hoth", 3): ["Boba Fett, Scion of Jango", "Clone Sergeant - Phase I", "Commander Ahsoka Tano", "Dark Trooper", "Darth Malgus", "Darth Traya", "Emperor's Shuttle", "Executor", "General Kenobi", "Jedi Master Luke Skywalker", "Rebel Officer Leia Organa", "Scythe", "Sith Eternal Emperor", "Veteran Smuggler Chewbacca", "Young Lando Calrissian"],
    ("Hoth", 4): ["Asajj Ventress", "B1 Battle Droid", "Darth Malgus", "Darth Malgus", "First Order Officer", "General Kenobi", "Han Solo", "HK-47", "Jedi Consular", "Lord Vader", "Lord Vader", "Scythe", "Supreme Leader Kylo Ren", "TIE Echelon", "Wat Tambor"],
    ("Hoth", 5): ["Ben Solo", "Boba Fett, Scion of Jango", "Commander Ahsoka Tano", "Han Solo", "Han Solo", "Hermit Yoda", "Hoth Rebel Scout", "Maul", "Nute Gunray", "Razor Crest", "Rey", "Rey", "Sana Starros", "Scythe", "Supreme Leader Kylo Ren"],
    ("Hoth", 6): ["Admiral Raddus", "Aurra Sing", "Ben Solo", "Chief Nebit", "Commander Ahsoka Tano", "Darth Malgus", "Dengar", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Lord Vader", "Nightsister Initiate", "Razor Crest", "Razor Crest", "Resistance Pilot", "Scythe"],
    # ---- Scarif ----
    ("Scarif", 1): ["Bastila Shan", "Biggs Darklighter's X-wing", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Commander Ahsoka Tano", "Coruscant Underworld Police", "Dash Rendar", "General Kenobi", "Hermit Yoda", "Jedi Master Kenobi", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Poe Dameron", "Raven's Claw", "Rebel Officer Leia Organa"],
    ("Scarif", 2): ["Bastila Shan", "Ben Solo", "Dash Rendar", "Ima-Gun Di", "Jedi Master Luke Skywalker", "Kanan Jarrus", "Lobot", "Outrider", "Raven's Claw", "Razor Crest", "Razor Crest", "Rey", "Rey", "Rey (Scavenger)", "The Mandalorian"],
    ("Scarif", 3): ["Bastila Shan", "Ben Solo", "Chewbacca", "Dash Rendar", "Grand Master Yoda", "Hermit Yoda", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "Padmé Amidala", "Raven's Claw", "Razor Crest", "Razor Crest", "Rebel Officer Leia Organa", "Rey"],
    ("Scarif", 4): ["Bastila Shan", "Ben Solo", "Commander Ahsoka Tano", "Dash Rendar", "Hermit Yoda", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "Ki-Adi-Mundi", "L3-37", "Mara Jade, The Emperor's Hand", "Razor Crest", "Rey", "Rey (Scavenger)", "Xanadu Blood"],
    ("Scarif", 5): ["Bastila Shan", "Ben Solo", "Ben Solo", "Han Solo", "Han Solo", "Ima-Gun Di", "Jedi Master Luke Skywalker", "Jedi Master Luke Skywalker", "Logray", "Razor Crest", "Resistance X-wing", "Rey", "Skiff Guard (Lando Calrissian)", "Tech", "Zaalbar"],
    ("Scarif", 6): ["Bastila Shan", "BB-8", "Ben Solo", "Ben Solo", "Dash Rendar", "Han Solo", "Han's Millennium Falcon", "Hermit Yoda", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Razor Crest", "Rebel Officer Leia Organa", "Rey", "Skiff Guard (Lando Calrissian)"],}

# Минимальная реликвия для донат-слота взвода — ПРИВЯЗАНА К ПЛАНЕТЕ, не к этапу гильдии.
# Прежняя версия справочника индексировалась по номеру этапа (round_num) со значениями
# 5/6/7/8/9/9 — это была живая выгрузка из Comlink territoryBattleDefinition (id="t05D"),
# где показалось, что unitRelicTier растёт по этапу и одинаков во всех ветках внутри
# этапа. По прямому запросу пользователя 2026-08-31 ("почему станция — это минимум р9?
# Медстанция вообще то минимум р8") выяснилось, что это неверно: минимум фиксирован ЗА
# ПЛАНЕТОЙ (одна и та же планета может стоять на разных этапах в разных планах гильдии —
# см. комментарий в начале файла — а минимум для неё не меняется). Пользователь
# подтвердил порядок планет по ветке (тёмная/микс/светлая, см. TB_PLANET_CONFLICT в
# cogs/guild_events.py) и сопоставил его с прежней шкалой 5/6/7/8/9/9 — т.е. позиция
# планеты внутри своей ветки задаёт её минимум, а не номер этапа, на который эту планету
# сейчас поставила гильдия.
ROTE_MIN_RELIC_BY_PLANET: dict[str, int] = {
    # Тёмная ветка (conflict01)
    "Mustafar": 5, "Geonosis": 6, "Dathomir": 7,
    "Haven-class Medical Station": 8, "Malachor": 9, "Death Star": 9,
    # Микс (conflict02)
    "Corellia": 5, "Felucia": 6, "Tatooine": 7,
    "Kessel": 8, "Vandor": 9, "Hoth": 9,
    # Светлая (conflict03)
    "Coruscant": 5, "Bracca": 6, "Kashyyyk": 7,
    "Lothal": 8, "Ring of Kafrene": 9, "Scarif": 9,
    # Бонус-зоны
    "Zeffo": 7, "Mandalore": 8,
}
